config/routes.rb
Rails.application.routes.draw do

  root 'application#index'

  match '/signup',            to: 'users#new',                    via: 'get'
  match '/signin',            to: 'sessions#new',                 via: 'get'
  match '/signout',           to: 'sessions#destroy',             via: 'delete'
  match '/home',              to: 'static_pages#home',            via: 'get'
  match '/save-answers.json', to: 'answers#save_from_submission', via: 'post'
  match '/submissions',       to: 'submissions#index',            via: 'get'
  match '/users',             to: 'users#index',                  via: 'get'
  match '/get-current-user',  to: 'users#get_current_user',       via: 'get'

  resources :questions

  resources :answers

  resources :contests

  resources :submissions

  resources :users

  resources :sessions,  only: [:create, :destroy]

  get '/app' => 'application#index'

end

app/models/contest.rb
class Contest < ActiveRecord::Base
  has_many :submissions
  has_many :questions
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  before_action :set_contest, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user
  
  # GET /contests
  # GET /contests.json
  def index
    @contests = Contest.all
  end

  # GET /contests/1
  # GET /contests/1.json
  def show
  end

  # GET /contests/new
  def new
    @contest = Contest.new
  end

  # GET /contests/1/edit
  def edit
  end

  # POST /contests
  # POST /contests.json
  def create
    @contest = Contest.new(contest_params)

    respond_to do |format|
      if @contest.save
        format.html { redirect_to @contest, notice: 'Contest was successfully created.' }
        format.json { render :show, status: :created, location: @contest }
      else
        format.html { render :new }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contests/1
  # PATCH/PUT /contests/1.json
  def update
    respond_to do |format|
      if @contest.update(contest_params)
        format.html { redirect_to @contest, notice: 'Contest was successfully updated.' }
        format.json { render :show, status: :ok, location: @contest }
      else
        format.html { render :edit }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contests/1
  # DELETE /contests/1.json
  def destroy
    @contest.destroy
    respond_to do |format|
      format.html { redirect_to contests_url, notice: 'Contest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contest
      @contest = Contest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contest_params
      params.require(:contest).permit(:title, :description, :end_date, :prize, :company)
    end
end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/views/contests/_form.html.erb
<%= form_for(@contest) do |f| %>
  <% if @contest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contest.errors.count, "error") %> prohibited this contest from being saved:</h2>

      <ul>
      <% @contest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.datetime_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :prize %><br>
    <%= f.number_field :prize %>
  </div>
  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contests/edit.html.erb
<h1>Editing contest</h1>

<%= render 'form' %>

<%= link_to 'Show', @contest %> |
<%= link_to 'Back', contests_path %>

app/views/contests/index.html.erb
<h1>Listing contests</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>End date</th>
      <th>Prize</th>
      <th>Company</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contests.each do |contest| %>
      <tr>
        <td><%= contest.title %></td>
        <td><%= contest.description %></td>
        <td><%= contest.end_date %></td>
        <td><%= contest.prize %></td>
        <td><%= contest.company %></td>
        <td><%= link_to 'Show', contest %></td>
        <td><%= link_to 'Edit', edit_contest_path(contest) %></td>
        <td><%= link_to 'Destroy', contest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contest', new_contest_path %>

app/views/contests/new.html.erb
<h1>New contest</h1>

<%= render 'form' %>

<%= link_to 'Back', contests_path %>

app/views/contests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @contest.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @contest.description %>
</p>

<p>
  <strong>End date:</strong>
  <%= @contest.end_date %>
</p>

<p>
  <strong>Prize:</strong>
  <%= @contest.prize %>
</p>

<p>
  <strong>Company:</strong>
  <%= @contest.company %>
</p>

<%= link_to 'Edit', edit_contest_path(@contest) %> |
<%= link_to 'Back', contests_path %>